# Generated by Django 4.1.2 on 2022-11-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('content', models.TextField(max_length=3000, verbose_name='Контент')),
                ('created_add', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_add', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
        ),
    ]
