# Generated by Django 4.1.2 on 2022-11-01 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='title1',
        ),
    ]
