# Generated by Django 4.1.2 on 2022-11-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_title1_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='Автор'),
        ),
    ]
