# Generated by Django 4.1.2 on 2022-11-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_tag_articletag_article_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tags',
            new_name='tags_old',
        ),
    ]
