# Generated by Django 4.1.2 on 2022-11-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_rename_tags_article_tags_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags_old',
            field=models.ManyToManyField(blank=True, related_name='article_set', through='webapp.ArticleTag', to='webapp.tag'),
        ),
    ]
