# Generated by Django 4.1.2 on 2022-11-18 14:20

from django.db import migrations


def transfer_tags(apps, schema_editor):
    Article = apps.get_model('webapp.Article')
    for article in Article.objects.all():
        article.tags.set(article.tags_old.all())


def rollback_transfer(apps, schema_editor):
    Article = apps.get_model('webapp.Article')
    for article in Article.objects.all():
        article.tags_old.set(article.tags.all())


class Migration(migrations.Migration):
    dependencies = [
        ('webapp', '0010_article_tags'),
    ]

    operations = [
        migrations.RunPython(transfer_tags, rollback_transfer)
    ]
