# Generated by Django 4.1.2 on 2022-11-23 13:45

from django.db import migrations, models
import webapp.validate


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_remove_article_tags_old_delete_articletag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=3000, validators=[webapp.validate.at_least_8], verbose_name='Контент'),
        ),
    ]
