# Generated by Django 4.1.2 on 2022-11-23 14:05

from django.db import migrations, models
import webapp.validate


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='Unknown', max_length=50, validators=[webapp.validate.MinLengthValidator(6)], verbose_name='Автор'),
        ),
    ]
