# Generated by Django 4.1.2 on 2022-12-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
