# Generated by Django 4.1.2 on 2022-12-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_article_author_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('сan_have_piece_of_pizza', 'Может съесть кусочек пиццы')]},
        ),
    ]
